---
- include_tasks: preflight.yml
  tags:
    - alertmanager_install
    - alertmanager_configure
    - alertmanager_run

- include_tasks: install.yml
  tags:
    - alertmanager_install
    - install

- import_tasks: selinux.yml
  become: true
  when: ansible_selinux.status == "enabled"
  tags:
    - alertmanager_configure
    - install

- include_tasks: configure.yml
  tags:
    - alertmanager_configure
    - configure

- name: ensure alertmanager service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: alertmanager
    state: started
    enabled: true
  tags:
    - alertmanager_run

- name: Flush alertmangaer handlers after run.
  meta: flush_handlers
